/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ocr_jni_Mser */

#ifndef _Included_com_ocr_jni_Mser
#define _Included_com_ocr_jni_Mser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ocr_jni_Mser
 * Method:    detectIdNum
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ocr_jni_Mser_detectIdNum
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
